server:
        certs:
                #put your certificates here
                chain: "chain.pem"
                key: "key.pem"
        #your server address here (for downloading new modules)
        address: "server.example/"
        download:
                path: "srekware/download"
                files: ["file1.py", "file2.py"]

